angular.module('StaticAdapter', [])

    .factory('StaticAdapter', function(
        LoadIncidentTypes_Static, LoadAllIncidents_Static, LoadIncident_Static, isLoggedIn_Static,
        LoadActionTypes_Static, LoadSectorTypes_Static, LoadUnitTypes_Static
    ) {
        return {
            adapter_id_str:'static',
            init:function(){return true;},
            LoadIncidentTypes: LoadIncidentTypes_Static,
            LoadAllIncidents: LoadAllIncidents_Static,
            LoadIncident: LoadIncident_Static,
            UpdateIncidentAsNeeded: function(){console.log("StaticAdapter UpdateIncidentAsNeeded");},
            isLoggedIn: isLoggedIn_Static,
            LoadActionTypes: LoadActionTypes_Static,
            LoadSectorTypes: LoadSectorTypes_Static,
            LoadUnitTypes: LoadUnitTypes_Static
        };
    })

    .factory('isLoggedIn_Static', function () {
        return function () {
            return true;
        }
    })

    .factory('LoadIncidentTypes_Static', function ($q) {
        return function () {
            var promise = $q.when(INC_TYPES);
            return promise;
        }
    })

    .factory('LoadAllIncidents_Static', function ($q) {
        return function () {
            var promise = $q.when(INCIDENTS);
            return promise;
        }
    })

    .factory('LoadIncident_Static', function ($q) {
        return function () {
            console.log("NOTE: You are using the Static Adapter so the inc_id config parameter is ignored.  The same incident data is always returned.");
            var promise = $q.when(INCIDENT);
            return promise;
        }
    })

    .factory('LoadActionTypes_Static', function ($q) {
        return function () {
            var promise = $q.when(ACTION_TYPES);
            return promise;
        }
    })

    .factory('LoadSectorTypes_Static', function ($q) {
        return function () {
            var promise = $q.when(SECTOR_TYPES);
            return promise;
        }
    })

    .factory('LoadUnitTypes_Static', function ($q) {
        return function () {
            var promise = $q.when(UNIT_TYPES);
            return promise;
        }
    })
;


var INC_TYPES = [
    {
        "type": "fire",
        "icon": "img/icons/fire.png",
        "nameLong": "Fire Incident",
        "order":1
    },
    {
        "type": "medical",
        "icon": "img/icons/medical.png",
        "nameLong": "Medical Incident",
        "order":2
    },
    {
        "type": "arff",
        "icon": "img/icons/plane.png",
        "nameLong": "ARFF Incident",
        "order":3
    },
    {
        "type": "hazmat",
        "icon": "img/icons/hazmat.png",
        "nameLong": "HazMat Incident",
        "order":4
    },
    {
        "type": "water",
        "icon": "img/icons/water.png",
        "nameLong": "Water Rescue",
        "order":5
    },
    {
        "type": "trench",
        "icon": "img/icons/trench.png",
        "nameLong": "Trench Rescue",
        "order":6
    },
    {
        "type": "mountain",
        "icon": "img/icons/mountain.png",
        "nameLong": "Mountain Rescue",
        "order":7
    },
    {
        "type": "palm",
        "icon": "img/icons/palm.png",
        "nameLong": "Palm Rescue",
        "order":8
    },
    {
        "type": "struct",
        "icon": "img/icons/structure.png",
        "nameLong": "Structural Rescue",
        "order":9
    },
    {
        "type": "confined",
        "icon": "img/icons/confined.png",
        "nameLong": "Confined Space Rescue",
        "order":10
    }
];

var INCIDENTS = [
    {
        "id":"inc_001_id",
        "inc_number":"inc_001",
        "incidentType": {
            "type": "fire",
            "icon": "img/icons/fire.png",
            "nameLong": "Fire Incident",
            "order":1
        }
    },
    {
        "id":"inc_002_id",
        "inc_number":"inc_002",
        "incidentType": {
            "type": "palm",
            "icon": "img/icons/palm.png",
            "nameLong": "Palm Rescue",
            "order":8
        }
    }
];

var INCIDENT = {
    "id":"inc_001_id",
    "inc_number":"inc_001",
    "incidentType": {
        "type": "fire",
        "icon": "img/icons/fire.png",
        "nameLong": "Fire Incident",
        "order":1
    }
}

var ACTION_TYPES = [
    {"action_type":"Engine", "is_warning":false, "name":"Supply"},
    {"action_type":"Engine", "is_warning":false, "name":"Take a Line"},
    {"action_type":"Engine", "is_warning":false, "name":"Search/Rescue"},
    {"action_type":"Engine", "is_warning":false, "name":"Fire Attack"},
    {"action_type":"Engine", "is_warning":false, "name":"IRIC"},
    {"action_type":"Engine", "is_warning":false, "name":"Check Extension"},
    {"action_type":"Engine", "is_warning":false, "name":"Protect Exposures"},
    {"action_type":"Engine", "is_warning":false, "name":"Overhaul"},
    {"action_type":"Engine", "is_warning":false, "name":"Deck Gun"},
    {"action_type":"Engine", "is_warning":false, "name":"Portable Monitor"},
    {"action_type":"Ladder", "is_warning":false, "name":"Secure Utilities"},
    {"action_type":"Ladder", "is_warning":false, "name":"Vert Ventilation"},
    {"action_type":"Ladder", "is_warning":false, "name":"Trench Cut"},
    {"action_type":"Ladder", "is_warning":false, "name":"Roof Profile"},
    {"action_type":"Ladder", "is_warning":false, "name":"Fan to the Door"},
    {"action_type":"Ladder", "is_warning":false, "name":"Soften Building"},
    {"action_type":"Ladder", "is_warning":false, "name":"Open Building"},
    {"action_type":"Ladder", "is_warning":false, "name":"Salvage"},
    {"action_type":"Ladder", "is_warning":false, "name":"Elevated Master"},
    {"action_type":"Safety", "is_warning":false, "name":"Agrees With Strategy"},
    {"action_type":"Safety", "is_warning":false, "name":"360 recon"},
    {"action_type":"Safety", "is_warning":true, "name":"*Pool"},
    {"action_type":"Safety", "is_warning":true, "name":"*Empty Pool"},
    {"action_type":"Safety", "is_warning":true, "name":"*Powerlines"},
    {"action_type":"Safety", "is_warning":true, "name":"*Powerlines Down"},
    {"action_type":"Safety", "is_warning":true, "name":"*Bars on Windows"},
    {"action_type":"Safety", "is_warning":true, "name":"*Dogs in Yard"},
    {"action_type":"Safety", "is_warning":true, "name":"*Hoarders House"},
    {"action_type":"Safety", "is_warning":true, "name":"*Basement"},
    {"action_type":"Rescue", "is_warning":false, "name":"Grab RIC Bag"},
    {"action_type":"Rescue", "is_warning":false, "name":"Accountability Update"},
    {"action_type":"Rescue", "is_warning":false, "name":"Throw Ladders"},
    {"action_type":"Lines", "is_warning":false, "name":"1-3/4"},
    {"action_type":"Lines", "is_warning":false, "name":"2\""},
    {"action_type":"Lines", "is_warning":false, "name":"2-1/2"},
    {"action_type":"Lines", "is_warning":false, "name":"3\""},
    {"action_type":"Lines", "is_warning":false, "name":"Piercing Nozzle"},
    {"action_type":"Lines", "is_warning":false, "name":"Horizontal Standpipe"},
    {"action_type":"Lines", "is_warning":false, "name":"Support Sprinklers"},
    {"action_type":"Lines", "is_warning":false, "name":"Standpipe"}
]

var SECTOR_TYPES = [
    {"name":"Interior", "hasClock":true, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Sector 1", "hasClock":true, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"North Sector", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"A-Side Sector", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},

    {"name":"", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Sector 2", "hasClock":true, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Eat Sector", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Bravo Sector", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},

    {"name":"Ventilation", "hasClock":true, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Sector 3", "hasClock":true, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"South Sector", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Charlie Sector", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},

    {"name":"Roof", "hasClock":true, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Sector 4", "hasClock":true, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"West Sector", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Delta Sector", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},

    {"name":"", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Sector ####", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},

    {"name":"", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},

    {"name":"On Deck", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Overhaul", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"IRIC", "hasClock":true, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Medical", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},

    {"name":"Staging", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Salvage", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"RIC", "hasClock":true, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Triage", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},

    {"name":"Lobby", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Customer Service", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"RESCUE", "hasClock":true, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Treatment", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},

    {"name":"Accountability", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Evacuation", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Safety", "hasClock":true, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Transportation", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},

    {"name":"", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"Resource", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true},
    {"name":"ReHab", "hasClock":false, "hasAcctBtn":false, "hasPsiBtn":false, "hasActions":false},
    {"name":"", "hasClock":false, "hasAcctBtn":true, "hasPsiBtn":true, "hasActions":true}

]

var UNIT_TYPES = [
    {"city":"Chandler", "type":"Engine", "unit":"E282"},
    {"city":"Chandler", "type":"Engine", "unit":"E283"},
    {"city":"Chandler", "type":"Engine", "unit":"E284"},
    {"city":"Chandler", "type":"Engine", "unit":"E285"},
    {"city":"Chandler", "type":"Engine", "unit":"E286"},
    {"city":"Chandler", "type":"Engine", "unit":"E287"},
    {"city":"Chandler", "type":"Engine", "unit":"E288"},
    {"city":"Chandler", "type":"Engine", "unit":"E289"},
    {"city":"Chandler", "type":"Engine", "unit":"E2810"},
    {"city":"Chandler", "type":"Engine", "unit":"E2282"},
    {"city":"Chandler", "type":"Ladder", "unit":"L281"},
    {"city":"Chandler", "type":"Ladder", "unit":"L283"},
    {"city":"Chandler", "type":"Ladder", "unit":"Lt281"},
    {"city":"Chandler", "type":"Ladder", "unit":"Lt283"},
    {"city":"Chandler", "type":"BC", "unit":"BC281"},
    {"city":"Chandler", "type":"BC", "unit":"BC282"},
    {"city":"Chandler", "type":"BC", "unit":"BSO281"},
    {"city":"Chandler", "type":"BC", "unit":"BSO282"},
    {"city":"Chandler", "type":"Squad", "unit":"SQ283"},
    {"city":"Chandler", "type":"HazMat", "unit":"HM283"},
    {"city":"Chandler", "type":"Util", "unit":"U288"},
    {"city":"Chandler", "type":"Brush", "unit":"Br284"},
    {"city":"Chandler", "type":"Ambo", "unit":"Ambo"},
    {"city":"Chandler", "type":"AirVac", "unit":"Native Air"},
    {"city":"Chandler", "type":"AirVac", "unit":"Life Net"},
    {"city":"Chandler", "type":"AirVac", "unit":"Ranger 41"},

    {"city":"Gilbert", "type":"Engine", "unit":"E251"},
    {"city":"Gilbert", "type":"Engine", "unit":"E252"},
    {"city":"Gilbert", "type":"Engine", "unit":"E254"},
    {"city":"Gilbert", "type":"Engine", "unit":"E256"},
    {"city":"Gilbert", "type":"Engine", "unit":"E257"},
    {"city":"Gilbert", "type":"Engine", "unit":"E258"},
    {"city":"Gilbert", "type":"Engine", "unit":"E2510"},
    {"city":"Gilbert", "type":"Engine", "unit":"E2511"},
    {"city":"Gilbert", "type":"Engine", "unit":"E2540"},
    {"city":"Gilbert", "type":"Ladder", "unit":"L210"},
    {"city":"Gilbert", "type":"Ladder", "unit":"L251"},
    {"city":"Gilbert", "type":"Ladder", "unit":"L253"},
    {"city":"Gilbert", "type":"Ladder", "unit":"L255"},
    {"city":"Gilbert", "type":"Ladder", "unit":"Lt251"},
    {"city":"Gilbert", "type":"Ladder", "unit":"Lt253"},
    {"city":"Gilbert", "type":"Ladder", "unit":"Lt255"},
    {"city":"Gilbert", "type":"BC", "unit":"BC251"},
    {"city":"Gilbert", "type":"BC", "unit":"BC252"},
    {"city":"Gilbert", "type":"BC", "unit":"BSO251"},
    {"city":"Gilbert", "type":"BC", "unit":"BSO252"},
    {"city":"Gilbert", "type":"Util", "unit":"U251"},
    {"city":"Gilbert", "type":"CV", "unit":"CV251"},
    {"city":"Gilbert", "type":"WtrTend", "unit":"WT256"},
    {"city":"Gilbert", "type":"WtrTend", "unit":"WT2511"},
    {"city":"Gilbert", "type":"HazMat", "unit":"HM258"},
    {"city":"Gilbert", "type":"Brush", "unit":"Br2511"},
    {"city":"Gilbert", "type":"Ambo", "unit":"SWA251"},
    {"city":"Gilbert", "type":"Ambo", "unit":"SWA252"},
    {"city":"Gilbert", "type":"Ambo", "unit":"SWA253"},
    {"city":"Gilbert", "type":"Ambo", "unit":"SWA255"},
    {"city":"Gilbert", "type":"AirVac", "unit":"Native Air"},
    {"city":"Gilbert", "type":"AirVac", "unit":"Life Net"},
    {"city":"Gilbert", "type":"AirVac", "unit":"Ranger 41"},

    {"city":"Mesa", "type":"Engine", "unit":"E201", "default":"1"},
    {"city":"Mesa", "type":"Engine", "unit":"E202"},
    {"city":"Mesa", "type":"Engine", "unit":"E203"},
    {"city":"Mesa", "type":"Engine", "unit":"E204"},
    {"city":"Mesa", "type":"Engine", "unit":"E205"},
    {"city":"Mesa", "type":"Engine", "unit":"E206"},
    {"city":"Mesa", "type":"Engine", "unit":"E207"},
    {"city":"Mesa", "type":"Engine", "unit":"E208"},
    {"city":"Mesa", "type":"Engine", "unit":"E209"},
    {"city":"Mesa", "type":"Engine", "unit":"E210"},
    {"city":"Mesa", "type":"Engine", "unit":"E211"},
    {"city":"Mesa", "type":"Engine", "unit":"E212"},
    {"city":"Mesa", "type":"Engine", "unit":"E213"},
    {"city":"Mesa", "type":"Engine", "unit":"E215"},
    {"city":"Mesa", "type":"Engine", "unit":"E216"},
    {"city":"Mesa", "type":"Engine", "unit":"E217"},
    {"city":"Mesa", "type":"Engine", "unit":"E218"},
    {"city":"Mesa", "type":"Engine", "unit":"E219"},
    {"city":"Mesa", "type":"Engine", "unit":"E220"},
    {"city":"Mesa", "type":"Engine", "unit":"E221"},
    {"city":"Mesa", "type":"Engine", "unit":"E222"},
    {"city":"Mesa", "type":"Engine", "unit":"E223"},
    {"city":"Mesa", "type":"Engine", "unit":"E224"},
    {"city":"Mesa", "type":"Engine", "unit":"E225"},
    {"city":"Mesa", "type":"Engine", "unit":"E226"},
    {"city":"Mesa", "type":"Engine", "unit":"E227"},
    {"city":"Mesa", "type":"Engine", "unit":"E228"},
    {"city":"Mesa", "type":"Engine", "unit":"E229"},
    {"city":"Mesa", "type":"Ladder", "unit":"L201"},
    {"city":"Mesa", "type":"Ladder", "unit":"L204"},
    {"city":"Mesa", "type":"Ladder", "unit":"L206"},
    {"city":"Mesa", "type":"Ladder", "unit":"L209"},
    {"city":"Mesa", "type":"Ladder", "unit":"L214"},
    {"city":"Mesa", "type":"Ladder", "unit":"L220"},
    {"city":"Mesa", "type":"Ladder", "unit":"Lt201"},
    {"city":"Mesa", "type":"Ladder", "unit":"Lt204"},
    {"city":"Mesa", "type":"Ladder", "unit":"Lt206"},
    {"city":"Mesa", "type":"Ladder", "unit":"Lt209"},
    {"city":"Mesa", "type":"Ladder", "unit":"Lt214"},
    {"city":"Mesa", "type":"Ladder", "unit":"Lt220"},
    {"city":"Mesa", "type":"BC", "unit":"ED200"},
    {"city":"Mesa", "type":"BC", "unit":"BC201"},
    {"city":"Mesa", "type":"BC", "unit":"BC202"},
    {"city":"Mesa", "type":"BC", "unit":"BC203"},
    {"city":"Mesa", "type":"BC", "unit":"BSO200"},
    {"city":"Mesa", "type":"BC", "unit":"BSO201"},
    {"city":"Mesa", "type":"BC", "unit":"BSO202"},
    {"city":"Mesa", "type":"BC", "unit":"BSO203"},
    {"city":"Mesa", "type":"Squad", "unit":"SQ204"},
    {"city":"Mesa", "type":"Squad", "unit":"SQ206"},
    {"city":"Mesa", "type":"ScnSup", "unit":"SS208"},
    {"city":"Mesa", "type":"WtrTend", "unit":"WT213"},
    {"city":"Mesa", "type":"Brush", "unit":"Br212"},
    {"city":"Mesa", "type":"Brush", "unit":"Br214"},
    {"city":"Mesa", "type":"Brush", "unit":"Br216"},
    {"city":"Mesa", "type":"Brush", "unit":"Br219"},
    {"city":"Mesa", "type":"Foam", "unit":"FO21"},
    {"city":"Mesa", "type":"Foam", "unit":"FO22"},
    {"city":"Mesa", "type":"Foam", "unit":"FO23"},
    {"city":"Mesa", "type":"Con", "unit":"Con201"},
    {"city":"Mesa", "type":"Con", "unit":"Con202"},
    {"city":"Mesa", "type":"Con", "unit":"Con203"},
    {"city":"Mesa", "type":"Util", "unit":"U202"},
    {"city":"Mesa", "type":"CV", "unit":"CV201"},
    {"city":"Mesa", "type":"HazMat", "unit":"HM206"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA201"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA202"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA203"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA204"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA205"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA206"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA207"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA208"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA209"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA210"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA211"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA212"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA220"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA221"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA222"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA223"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA224"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA225"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA226"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA227"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA228"},
    {"city":"Mesa", "type":"Ambo", "unit":"SWA229"},
    {"city":"Mesa", "type":"AirVac", "unit":"Native Air"},
    {"city":"Mesa", "type":"AirVac", "unit":"Life Net"},
    {"city":"Mesa", "type":"AirVac", "unit":"Ranger 41"},

    {"city":"QC", "type":"Engine", "unit":"E411"},
    {"city":"QC", "type":"Engine", "unit":"E412"},
    {"city":"QC", "type":"BC", "unit":"BC411"},
    {"city":"QC", "type":"BC", "unit":"BSO411"},
    {"city":"QC", "type":"Ambo", "unit":"SWA411"},
    {"city":"QC", "type":"AirVac", "unit":"Native Air"},
    {"city":"QC", "type":"AirVac", "unit":"Life Net"},
    {"city":"QC", "type":"AirVac", "unit":"Ranger 41"},

    {"city":"Phoenix", "type":"Engine", "unit":"E1"},
    {"city":"Phoenix", "type":"Engine", "unit":"E3"},
    {"city":"Phoenix", "type":"Engine", "unit":"E4"},
    {"city":"Phoenix", "type":"Engine", "unit":"E5"},
    {"city":"Phoenix", "type":"Engine", "unit":"E6"},
    {"city":"Phoenix", "type":"Engine", "unit":"E7"},
    {"city":"Phoenix", "type":"Engine", "unit":"E8"},
    {"city":"Phoenix", "type":"Engine", "unit":"E9"},
    {"city":"Phoenix", "type":"Engine", "unit":"E10"},
    {"city":"Phoenix", "type":"Engine", "unit":"E11"},
    {"city":"Phoenix", "type":"Engine", "unit":"E12"},
    {"city":"Phoenix", "type":"Engine", "unit":"E13"},
    {"city":"Phoenix", "type":"Engine", "unit":"E14"},
    {"city":"Phoenix", "type":"Engine", "unit":"E15"},
    {"city":"Phoenix", "type":"Engine", "unit":"E16"},
    {"city":"Phoenix", "type":"Engine", "unit":"E17"},
    {"city":"Phoenix", "type":"Engine", "unit":"E18"},
    {"city":"Phoenix", "type":"Engine", "unit":"E19"},
    {"city":"Phoenix", "type":"Engine", "unit":"E20"},
    {"city":"Phoenix", "type":"Engine", "unit":"E21"},
    {"city":"Phoenix", "type":"Engine", "unit":"E22"},
    {"city":"Phoenix", "type":"Engine", "unit":"E23"},
    {"city":"Phoenix", "type":"Engine", "unit":"E24"},
    {"city":"Phoenix", "type":"Engine", "unit":"E25"},
    {"city":"Phoenix", "type":"Engine", "unit":"E26"},
    {"city":"Phoenix", "type":"Engine", "unit":"E27"},
    {"city":"Phoenix", "type":"Engine", "unit":"E28"},
    {"city":"Phoenix", "type":"Engine", "unit":"E29"},
    {"city":"Phoenix", "type":"Engine", "unit":"E30"},
    {"city":"Phoenix", "type":"Engine", "unit":"E31"},
    {"city":"Phoenix", "type":"Engine", "unit":"E32"},
    {"city":"Phoenix", "type":"Engine", "unit":"E33"},
    {"city":"Phoenix", "type":"Engine", "unit":"E34"},
    {"city":"Phoenix", "type":"Engine", "unit":"E35"},
    {"city":"Phoenix", "type":"Engine", "unit":"E36"},
    {"city":"Phoenix", "type":"Engine", "unit":"E37"},
    {"city":"Phoenix", "type":"Engine", "unit":"E38"},
    {"city":"Phoenix", "type":"Engine", "unit":"E39"},
    {"city":"Phoenix", "type":"Engine", "unit":"E40"},
    {"city":"Phoenix", "type":"Engine", "unit":"E41"},
    {"city":"Phoenix", "type":"Engine", "unit":"E42"},
    {"city":"Phoenix", "type":"Engine", "unit":"E43"},
    {"city":"Phoenix", "type":"Engine", "unit":"E44"},
    {"city":"Phoenix", "type":"Engine", "unit":"E45"},
    {"city":"Phoenix", "type":"Engine", "unit":"E46"},
    {"city":"Phoenix", "type":"Engine", "unit":"E48"},
    {"city":"Phoenix", "type":"Engine", "unit":"E49"},
    {"city":"Phoenix", "type":"Engine", "unit":"E50"},
    {"city":"Phoenix", "type":"Engine", "unit":"E52"},
    {"city":"Phoenix", "type":"Engine", "unit":"E54"},
    {"city":"Phoenix", "type":"Engine", "unit":"E56"},
    {"city":"Phoenix", "type":"Engine", "unit":"E57"},
    {"city":"Phoenix", "type":"Engine", "unit":"E58"},
    {"city":"Phoenix", "type":"Engine", "unit":"E59"},
    {"city":"Phoenix", "type":"Engine", "unit":"E60"},
    {"city":"Phoenix", "type":"Engine", "unit":"E61"},
    {"city":"Phoenix", "type":"Engine", "unit":"E72"},
    {"city":"Phoenix", "type":"Engine", "unit":"E905"},
    {"city":"Phoenix", "type":"Engine", "unit":"E910"},
    {"city":"Phoenix", "type":"Engine", "unit":"E918"},
    {"city":"Phoenix", "type":"Engine", "unit":"E925"},
    {"city":"Phoenix", "type":"Engine", "unit":"E929"},
    {"city":"Phoenix", "type":"Engine", "unit":"E930"},
    {"city":"Phoenix", "type":"Engine", "unit":"E935"},
    {"city":"Phoenix", "type":"Engine", "unit":"E960"},
    {"city":"Phoenix", "type":"Ladder", "unit":"L1"},
    {"city":"Phoenix", "type":"Ladder", "unit":"L4"},
    {"city":"Phoenix", "type":"Ladder", "unit":"L9"},
    {"city":"Phoenix", "type":"Ladder", "unit":"L11"},
    {"city":"Phoenix", "type":"Ladder", "unit":"L12"},
    {"city":"Phoenix", "type":"Ladder", "unit":"L20"},
    {"city":"Phoenix", "type":"Ladder", "unit":"L22"},
    {"city":"Phoenix", "type":"Ladder", "unit":"L24"},
    {"city":"Phoenix", "type":"Ladder", "unit":"L26"},
    {"city":"Phoenix", "type":"Ladder", "unit":"L33"},
    {"city":"Phoenix", "type":"Ladder", "unit":"L37"},
    {"city":"Phoenix", "type":"Ladder", "unit":"L41"},
    {"city":"Phoenix", "type":"Ladder", "unit":"L43"},
    {"city":"Phoenix", "type":"Ladder", "unit":"L50"},
    {"city":"Phoenix", "type":"Ladder", "unit":"Lt1"},
    {"city":"Phoenix", "type":"Ladder", "unit":"Lt4"},
    {"city":"Phoenix", "type":"Ladder", "unit":"Lt9"},
    {"city":"Phoenix", "type":"Ladder", "unit":"Lt11"},
    {"city":"Phoenix", "type":"Ladder", "unit":"Lt12"},
    {"city":"Phoenix", "type":"Ladder", "unit":"Lt20"},
    {"city":"Phoenix", "type":"Ladder", "unit":"Lt22"},
    {"city":"Phoenix", "type":"Ladder", "unit":"Lt24"},
    {"city":"Phoenix", "type":"Ladder", "unit":"Lt26"},
    {"city":"Phoenix", "type":"Ladder", "unit":"Lt33"},
    {"city":"Phoenix", "type":"Ladder", "unit":"Lt37"},
    {"city":"Phoenix", "type":"Ladder", "unit":"Lt41"},
    {"city":"Phoenix", "type":"Ladder", "unit":"Lt43"},
    {"city":"Phoenix", "type":"Ladder", "unit":"Lt50"},
    {"city":"Phoenix", "type":"BC", "unit":"BC1"},
    {"city":"Phoenix", "type":"BC", "unit":"BC2"},
    {"city":"Phoenix", "type":"BC", "unit":"BC3"},
    {"city":"Phoenix", "type":"BC", "unit":"BC4"},
    {"city":"Phoenix", "type":"BC", "unit":"BC5"},
    {"city":"Phoenix", "type":"BC", "unit":"BC6"},
    {"city":"Phoenix", "type":"BC", "unit":"BC8"},
    {"city":"Phoenix", "type":"BC", "unit":"BC19"},
    {"city":"Phoenix", "type":"BC", "unit":"No Dep"},
    {"city":"Phoenix", "type":"BC", "unit":"So Dep"},
    {"city":"Phoenix", "type":"BC", "unit":"BSO1"},
    {"city":"Phoenix", "type":"BC", "unit":"BSO2"},
    {"city":"Phoenix", "type":"BC", "unit":"BSO3"},
    {"city":"Phoenix", "type":"BC", "unit":"BSO4"},
    {"city":"Phoenix", "type":"BC", "unit":"BSO5"},
    {"city":"Phoenix", "type":"BC", "unit":"BSO6"},
    {"city":"Phoenix", "type":"BC", "unit":"BSO8"},
    {"city":"Phoenix", "type":"BC", "unit":"BSO19"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES3"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES5"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES7"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES8"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES9"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES11"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES12"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES13"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES15"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES16"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES17"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES18"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES21"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES22"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES25"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES26"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES27"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES28"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES29"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES30"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES31"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES32"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES33"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES34"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES35"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES36"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES38"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES40"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES42"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES43"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES45"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES50"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES60"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES918"},
    {"city":"Phoenix", "type":"Ambo", "unit":"RES942"},
    {"city":"Phoenix", "type":"Brush", "unit":"BT23"},
    {"city":"Phoenix", "type":"Brush", "unit":"BT28"},
    {"city":"Phoenix", "type":"Brush", "unit":"BT33"},
    {"city":"Phoenix", "type":"Brush", "unit":"BT35"},
    {"city":"Phoenix", "type":"Brush", "unit":"BT36"},
    {"city":"Phoenix", "type":"Brush", "unit":"BT45"},
    {"city":"Phoenix", "type":"Brush", "unit":"BT46"},
    {"city":"Phoenix", "type":"Brush", "unit":"BT48"},
    {"city":"Phoenix", "type":"Brush", "unit":"BT49"},
    {"city":"Phoenix", "type":"Brush", "unit":"BT52"},
    {"city":"Phoenix", "type":"Brush", "unit":"BT56"},
    {"city":"Phoenix", "type":"Brush", "unit":"BT57"},
    {"city":"Phoenix", "type":"Brush", "unit":"BT58"},
    {"city":"Phoenix", "type":"HazMat", "unit":"HM4"},
    {"city":"Phoenix", "type":"HazMat", "unit":"HM38"},
    {"city":"Phoenix", "type":"HazMat", "unit":"HM41"},
    {"city":"Phoenix", "type":"Util", "unit":"U10"},
    {"city":"Phoenix", "type":"Util", "unit":"U29"},
    {"city":"Phoenix", "type":"Util", "unit":"U50"},
    {"city":"Phoenix", "type":"Squad", "unit":"SQ8"},
    {"city":"Phoenix", "type":"Squad", "unit":"SQ44"},
    {"city":"Phoenix", "type":"Squad", "unit":"SQ72"},
    {"city":"Phoenix", "type":"SupVeh", "unit":"SV8"},
    {"city":"Phoenix", "type":"SupVeh", "unit":"SV12"},
    {"city":"Phoenix", "type":"SupVeh", "unit":"SV45"},
    {"city":"Phoenix", "type":"Foam", "unit":"Foam1"},
    {"city":"Phoenix", "type":"Foam", "unit":"Foam2"},
    {"city":"Phoenix", "type":"Foam", "unit":"Foam3"},
    {"city":"Phoenix", "type":"Foam", "unit":"Foam34"},
    {"city":"Phoenix", "type":"Foam", "unit":"Foam44"},
    {"city":"Phoenix", "type":"WtrTend", "unit":"WT23"},
    {"city":"Phoenix", "type":"WtrTend", "unit":"WT36"},
    {"city":"Phoenix", "type":"WtrTend", "unit":"WT52"},
    {"city":"Phoenix", "type":"WtrTend", "unit":"WT54"},
    {"city":"Phoenix", "type":"WtrTend", "unit":"WT56"},
    {"city":"Phoenix", "type":"WtrTend", "unit":"WT58"},
    {"city":"Phoenix", "type":"CV", "unit":"CV1"},
    {"city":"Phoenix", "type":"CV", "unit":"CV2"},
    {"city":"Phoenix", "type":"Hose", "unit":"Hose34"},
    {"city":"Phoenix", "type":"Hose", "unit":"Hose58"},
    {"city":"Phoenix", "type":"Vent", "unit":"Vent3"},
    {"city":"Phoenix", "type":"Crisis", "unit":"Cris16"},
    {"city":"Phoenix", "type":"HighRise", "unit":"HiRi1"},
    {"city":"Phoenix", "type":"PIO", "unit":"PI3"},
    {"city":"Phoenix", "type":"Attack", "unit":"Att19"},
    {"city":"Phoenix", "type":"AirVac", "unit":"Native Air"},
    {"city":"Phoenix", "type":"AirVac", "unit":"Life Net"},
    {"city":"Phoenix", "type":"AirVac", "unit":"Ranger 41"},

    {"city":"Suprstion", "type":"Engine", "unit":"E261"},
    {"city":"Suprstion", "type":"Engine", "unit":"E262"},
    {"city":"Suprstion", "type":"Engine", "unit":"E265"},
    {"city":"Suprstion", "type":"Ladder", "unit":"L263"},
    {"city":"Suprstion", "type":"Ladder", "unit":"L264"},
    {"city":"Suprstion", "type":"Ladder", "unit":"Lt263"},
    {"city":"Suprstion", "type":"Ladder", "unit":"Lt264"},
    {"city":"Suprstion", "type":"BC", "unit":"BC261"},
    {"city":"Suprstion", "type":"BC", "unit":"BSO261"},
    {"city":"Suprstion", "type":"WtrTend", "unit":"WT261"},
    {"city":"Suprstion", "type":"Brush", "unit":"BR261"},
    {"city":"Suprstion", "type":"Rehab", "unit":"RH261"},
    {"city":"Suprstion", "type":"Ambo", "unit":"SWA261"},
    {"city":"Suprstion", "type":"Ambo", "unit":"SWA262"},
    {"city":"Suprstion", "type":"Ambo", "unit":"SWA265"},
    {"city":"Suprstion", "type":"AirVac", "unit":"Native Air"},
    {"city":"Suprstion", "type":"AirVac", "unit":"Life Net"},
    {"city":"Suprstion", "type":"AirVac", "unit":"Ranger 41"},

    {"city":"Tempe", "type":"Engine", "unit":"E271"},
    {"city":"Tempe", "type":"Engine", "unit":"E272"},
    {"city":"Tempe", "type":"Engine", "unit":"E273"},
    {"city":"Tempe", "type":"Engine", "unit":"E274"},
    {"city":"Tempe", "type":"Engine", "unit":"E275"},
    {"city":"Tempe", "type":"Engine", "unit":"E276"},
    {"city":"Tempe", "type":"Engine", "unit":"E277"},
    {"city":"Tempe", "type":"Engine", "unit":"E278"},
    {"city":"Tempe", "type":"Ladder", "unit":"L273"},
    {"city":"Tempe", "type":"Ladder", "unit":"L276"},
    {"city":"Tempe", "type":"Ladder", "unit":"Lt273"},
    {"city":"Tempe", "type":"Ladder", "unit":"Lt276"},
    {"city":"Tempe", "type":"BC", "unit":"BC271"},
    {"city":"Tempe", "type":"BC", "unit":"BSO271"},
    {"city":"Tempe", "type":"SpecInc", "unit":"SI272"},
    {"city":"Tempe", "type":"ScnSup", "unit":"SS274"},
    {"city":"Tempe", "type":"SupVeh", "unit":"SV276"},
    {"city":"Tempe", "type":"FireBt", "unit":"FB271"},
    {"city":"Tempe", "type":"Squad", "unit":"SQ271"},
    {"city":"Tempe", "type":"HazMat", "unit":"HM272"},
    {"city":"Tempe", "type":"Medic", "unit":"Med271"},
    {"city":"Tempe", "type":"Medic", "unit":"Med272"},
    {"city":"Tempe", "type":"Medic", "unit":"Med276"},
    {"city":"Tempe", "type":"AirVac", "unit":"Native Air"},
    {"city":"Tempe", "type":"AirVac", "unit":"Life Net"},
    {"city":"Tempe", "type":"AirVac", "unit":"Ranger 41"}
]

